Algoritmo "10° exercicio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
numA, numB : caracter


Inicio
escreval("digite o 1° numero")
 leia(numA)
 
escreval(" Digite o 2° numero")
 leia(numB)
 
 escreval(numB, " e ",  numA)

Fimalgoritmo