Algoritmo "12° exercicio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
nome :caracter
dias, n1 : inteiro



Inicio
escreval("Digite seu nome: ")
leia(nome)

escreval("Digite sua idade: ")
leia(n1)

dias <- n1 * 360
escreval(nome, ", você viveu", dias, " dias no total")

Fimalgoritmo