Algoritmo "1° exercicio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
nome, sobrenome, soma : caracter

Inicio
 escreval("Qual é o seu nome?")
  leia(nome)
  
 escreval("qual é o seu sobrenome?")
  leia(sobrenome)
  
 soma <- nome + sobrenome
  escreval("Seu nome comnpleto é: ", soma)
 



Fimalgoritmo