Algoritmo "7° exercicio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
temp1 : caracter


Inicio
 escreval("Qual a temperatura de hoje meu consagrado?")
   leia(temp1)

 se temp1 >= 26 entao
   escreval("Hoje o dia esta quente")
 senao
   escreval("Hoje está fresco")
fimse


Fimalgoritmo