Algoritmo "multiplica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
multiplica , numero1 , numero2 : inteiro

Inicio
 escreva("Digite o primeiro numero")
 leia(numero1)

 escreva("Digite o segundo numero")
 leia(numero2)

 multiplica <- numero1 * numero2

 escreva(multiplica)

Fimalgoritmo