Algoritmo "operadores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2020
Var
  x : logico // verdadeiro ou falso
  n1 , n2 : inteiro  //numero inteiro
Inicio
   escreva("Digite o primeiro numero: ")
   leia(n1)
   
   escreva("Digite o segundo numero: ")
   leia(n2)

   x <- n1 = n2
   
   escreva(x)
   
Fimalgoritmo