Algoritmo "subtrsir"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
subtrair , numero1 , numero2 : inteiro


Inicio
 escreva("Digite o primeiro numero")
 leia(numero1)

 escreva("Digite o segundo numero")
 leia(numero2)

  subtrair <- numero1 - numero2

 escreva(subtrair)



Fimalgoritmo