Algoritmo "1° exercicio list.2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
num : inteiro

Inicio
  escreval("Digite um número: ")
  leia(num)
  
  se num mod 2 = 0 entao
   escreval("O numero", num, " é par")
  senao
   escreval("O numero", num, " é impar")
  fimse

Fimalgoritmo