Algoritmo "2° exercicio list.2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
temp1 : inteiro


Inicio
 escreval("Qual a temperatura de hoje?")
 leia(temp1)
 
 se temp1 >= 25 entao
  escreval("Hoje está quente")
 senao
  escreval("Hoje esá agradável")
fimse


Fimalgoritmo