Algoritmo "4° exercicio list.2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
vf , vv : inteiro


Inicio
escreval("Qual o seu valor fixo?")
leia(vf)

escreval("Qual valor você atingiu?")
leia(vv)

se vv >= vf entao
 escreval("Ganhouuu!!!")
senao
 escreval("perdeuuu!!!")
fimse

Fimalgoritmo